numList = [0, 1, 2, 3, 4]

print numList[2:4]
print numList[2:]
print numList[:5]
print numList[-2:]
print numList[:-2]
print numList[:]
print numList[::2]
print numList[1:5:2]
print numList[::-2]
print numList[-1:-5:-2]